/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhilosophieRouteImport } from './routes/philosophie'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PieceRefRouteImport } from './routes/piece.$ref'

const PhilosophieRoute = PhilosophieRouteImport.update({
  id: '/philosophie',
  path: '/philosophie',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PieceRefRoute = PieceRefRouteImport.update({
  id: '/piece/$ref',
  path: '/piece/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/philosophie': typeof PhilosophieRoute
  '/piece/$ref': typeof PieceRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/philosophie': typeof PhilosophieRoute
  '/piece/$ref': typeof PieceRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/philosophie': typeof PhilosophieRoute
  '/piece/$ref': typeof PieceRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/philosophie' | '/piece/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/philosophie' | '/piece/$ref'
  id: '__root__' | '/' | '/collection' | '/philosophie' | '/piece/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  PhilosophieRoute: typeof PhilosophieRoute
  PieceRefRoute: typeof PieceRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/philosophie': {
      id: '/philosophie'
      path: '/philosophie'
      fullPath: '/philosophie'
      preLoaderRoute: typeof PhilosophieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piece/$ref': {
      id: '/piece/$ref'
      path: '/piece/$ref'
      fullPath: '/piece/$ref'
      preLoaderRoute: typeof PieceRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  PhilosophieRoute: PhilosophieRoute,
  PieceRefRoute: PieceRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
